#include "hal_data.h"
#include "app.h"
#include <stdio.h>
#include <string.h>

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

#define AUDIO_FRAME_SAMPLES             (320U)
#define AUDIO_STATUS_UPDATE_INTERVAL    (10U)
#define AUDIO_LEVEL_TRIGGER             (300U)

#define DISPLAY_STATUS_CTRL             "g0"
#define DISPLAY_LEVEL_CTRL              "g1"
#define DISPLAY_HINT_CTRL               "g2"

typedef enum e_audio_runtime_state
{
    AUDIO_RUNTIME_BOOT = 0,
    AUDIO_RUNTIME_LISTENING,
    AUDIO_RUNTIME_ACTIVITY
} audio_runtime_state_t;

static int16_t g_audio_rx_buffer[AUDIO_FRAME_SAMPLES];
static int16_t g_audio_tx_dummy[AUDIO_FRAME_SAMPLES];
static volatile bool g_audio_frame_ready = false;
static volatile uint32_t g_audio_rx_events = 0;
static volatile uint32_t g_audio_error_events = 0;
static audio_runtime_state_t g_audio_state = AUDIO_RUNTIME_BOOT;

static void audio_display_text(const char *control, const char *text);
static void audio_display_value(const char *control, uint32_t value);
static void audio_display_state(audio_runtime_state_t state);
static fsp_err_t audio_frontend_init(void);
static fsp_err_t audio_frontend_start_frame(void);
static uint32_t audio_calculate_level(const int16_t *buffer, uint32_t samples);
static void audio_process_frame(void);

void g_i2s0_callback(i2s_callback_args_t *p_args)
{
    if (NULL == p_args)
    {
        return;
    }

    if (I2S_EVENT_RX_FULL == p_args->event)
    {
        g_audio_frame_ready = true;
        g_audio_rx_events++;
    }
    else if (I2S_EVENT_IDLE == p_args->event)
    {
        g_audio_error_events++;
    }
}

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    fsp_err_t err;

    err = drv_uart7_init();
    if (FSP_SUCCESS != err)
    {
        __BKPT();
    }

    err = app_tjc_display_init();
    if (FSP_SUCCESS != err)
    {
        __BKPT();
    }

    audio_display_text(DISPLAY_HINT_CTRL, "Audio frontend init");

    err = audio_frontend_init();
    if (FSP_SUCCESS != err)
    {
        audio_display_text(DISPLAY_STATUS_CTRL, "I2S init failed");
        __BKPT();
    }

    audio_display_text(DISPLAY_HINT_CTRL, "Mic stream active");
    audio_display_state(AUDIO_RUNTIME_LISTENING);

    while (1)
    {
        if (g_audio_frame_ready)
        {
            g_audio_frame_ready = false;
            audio_process_frame();

            err = audio_frontend_start_frame();
            if (FSP_SUCCESS != err)
            {
                audio_display_text(DISPLAY_STATUS_CTRL, "I2S restart failed");
                printf("I2S restart failed: %d\n", err);
                R_BSP_SoftwareDelay(200, BSP_DELAY_UNITS_MILLISECONDS);
            }
        }

        R_BSP_SoftwareDelay(5, BSP_DELAY_UNITS_MILLISECONDS);
    }
    
#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

static void audio_display_text(const char *control, const char *text)
{
    char cmd[128];

    if ((NULL == control) || (NULL == text))
    {
        return;
    }

    snprintf(cmd, sizeof(cmd), "%s.txt=\"%s\"", control, text);
    uart2_printf(cmd);
    uart2_putchar(0xFF);
    uart2_putchar(0xFF);
    uart2_putchar(0xFF);
}

static void audio_display_value(const char *control, uint32_t value)
{
    char cmd[64];

    if (NULL == control)
    {
        return;
    }

    snprintf(cmd, sizeof(cmd), "%s.txt=\"%lu\"", control, (unsigned long) value);
    uart2_printf(cmd);
    uart2_putchar(0xFF);
    uart2_putchar(0xFF);
    uart2_putchar(0xFF);
}

static void audio_display_state(audio_runtime_state_t state)
{
    switch (state)
    {
        case AUDIO_RUNTIME_BOOT:
        {
            audio_display_text(DISPLAY_STATUS_CTRL, "BOOT");
            break;
        }

        case AUDIO_RUNTIME_LISTENING:
        {
            audio_display_text(DISPLAY_STATUS_CTRL, "LISTEN");
            break;
        }

        case AUDIO_RUNTIME_ACTIVITY:
        {
            audio_display_text(DISPLAY_STATUS_CTRL, "VOICE");
            break;
        }

        default:
        {
            audio_display_text(DISPLAY_STATUS_CTRL, "UNKNOWN");
            break;
        }
    }
}

static fsp_err_t audio_frontend_init(void)
{
    fsp_err_t err;

    memset(g_audio_rx_buffer, 0, sizeof(g_audio_rx_buffer));
    memset(g_audio_tx_dummy, 0, sizeof(g_audio_tx_dummy));
    g_audio_frame_ready = false;
    g_audio_rx_events = 0;
    g_audio_error_events = 0;
    g_audio_state = AUDIO_RUNTIME_BOOT;

    err = g_i2s0.p_api->open(g_i2s0.p_ctrl, g_i2s0.p_cfg);
    if (FSP_SUCCESS != err)
    {
        printf("g_i2s0 open failed: %d\n", err);
        return err;
    }

    return audio_frontend_start_frame();
}

static fsp_err_t audio_frontend_start_frame(void)
{
    return g_i2s0.p_api->writeRead(g_i2s0.p_ctrl, g_audio_tx_dummy, g_audio_rx_buffer, sizeof(g_audio_rx_buffer));
}

static uint32_t audio_calculate_level(const int16_t *buffer, uint32_t samples)
{
    uint32_t sum = 0;

    for (uint32_t i = 0; i < samples; i++)
    {
        int32_t sample = buffer[i];

        if (sample < 0)
        {
            sample = -sample;
        }

        sum += (uint32_t) sample;
    }

    return sum / samples;
}

static void audio_process_frame(void)
{
    static uint32_t display_counter = 0;
    uint32_t level = audio_calculate_level(g_audio_rx_buffer, AUDIO_FRAME_SAMPLES);

    if (level > AUDIO_LEVEL_TRIGGER)
    {
        g_audio_state = AUDIO_RUNTIME_ACTIVITY;
    }
    else
    {
        g_audio_state = AUDIO_RUNTIME_LISTENING;
    }

    display_counter++;

    if ((display_counter % AUDIO_STATUS_UPDATE_INTERVAL) == 0U)
    {
        audio_display_state(g_audio_state);
        audio_display_value(DISPLAY_LEVEL_CTRL, level);

        if (g_audio_error_events > 0U)
        {
            audio_display_text(DISPLAY_HINT_CTRL, "Check I2S config");
        }
        else if (g_audio_state == AUDIO_RUNTIME_ACTIVITY)
        {
            audio_display_text(DISPLAY_HINT_CTRL, "Voice activity");
        }
        else
        {
            audio_display_text(DISPLAY_HINT_CTRL, "Waiting wake word");
        }

        printf("I2S frames=%lu level=%lu errors=%lu\n",
               (unsigned long) g_audio_rx_events,
               (unsigned long) level,
               (unsigned long) g_audio_error_events);
    }
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&g_ioport_ctrl, &IOPORT_CFG_NAME);
    }
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
