#include "hal_data.h"
#include "app.h"
#include "app_ai_config.h"
#include "net_client.h"
#include <stdio.h>
#include <string.h>

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

#define AUDIO_FRAME_SAMPLES             (320U)
#define AUDIO_STATUS_UPDATE_INTERVAL    (10U)
#define AUDIO_WAKE_LEVEL_TRIGGER        (380U)
#define AUDIO_WAKE_CONSECUTIVE_FRAMES   (3U)
#define AUDIO_RECORD_TARGET_FRAMES      (40U)
#define AUDIO_RESULT_HOLD_FRAMES        (80U)
#define AUDIO_COOLDOWN_FRAMES           (60U)
#define WIFI_API_TEST_ENABLE            (1)

#define DISPLAY_STATUS_CTRL             "g0"
#define DISPLAY_LEVEL_CTRL              "g1"
#define DISPLAY_HINT_CTRL               "g2"

typedef enum e_audio_runtime_state
{
    AUDIO_RUNTIME_BOOT = 0,
    AUDIO_RUNTIME_LISTENING,
    AUDIO_RUNTIME_WAKEUP,
    AUDIO_RUNTIME_RECORDING,
    AUDIO_RUNTIME_ASR,
    AUDIO_RUNTIME_TRANSLATE,
    AUDIO_RUNTIME_SHOW_RESULT,
    AUDIO_RUNTIME_ERROR
} audio_runtime_state_t;

static int16_t g_audio_rx_buffer[AUDIO_FRAME_SAMPLES];
static int16_t g_audio_tx_dummy[AUDIO_FRAME_SAMPLES];
static volatile bool g_audio_frame_ready = false;
static volatile uint32_t g_audio_rx_events = 0;
static volatile uint32_t g_audio_error_events = 0;
static audio_runtime_state_t g_audio_state = AUDIO_RUNTIME_BOOT;
static bool g_cloud_connected = false;
static uint32_t g_wake_streak = 0;
static uint32_t g_record_frame_count = 0;
static uint32_t g_record_level_sum = 0;
static uint32_t g_result_hold_count = 0;
static uint32_t g_cooldown_count = 0;
static char g_source_text[96];
static char g_translated_text[128];

static void audio_copy_display_text(char *dest, uint32_t dest_size, const char *text);
static void audio_display_text(const char *control, const char *text);
static void audio_display_state(audio_runtime_state_t state);
static void audio_show_translation_lines(void);
static void wifi_api_test_run(void);
static void audio_state_set(audio_runtime_state_t state);
static void audio_reset_capture_session(void);
static fsp_err_t audio_cloud_prepare(void);
static fsp_err_t audio_frontend_init(void);
static fsp_err_t audio_frontend_start_frame(void);
static uint32_t audio_calculate_level(const int16_t *buffer, uint32_t samples);
static void audio_process_frame(void);

void g_i2s0_callback(i2s_callback_args_t *p_args)
{
    if (NULL == p_args)
    {
        return;
    }

    if (I2S_EVENT_RX_FULL == p_args->event)
    {
        g_audio_frame_ready = true;
        g_audio_rx_events++;
    }
    else if (I2S_EVENT_IDLE == p_args->event)
    {
        g_audio_error_events++;
    }
}

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    fsp_err_t err;

    err = drv_uart7_init();
    if (FSP_SUCCESS != err)
    {
        __BKPT();
    }

    err = app_tjc_display_init();
    if (FSP_SUCCESS != err)
    {
        __BKPT();
    }

#if WIFI_API_TEST_ENABLE
    wifi_api_test_run();
    while (1)
    {
        R_BSP_SoftwareDelay(500, BSP_DELAY_UNITS_MILLISECONDS);
    }
#endif

    audio_display_text(DISPLAY_HINT_CTRL, "Audio frontend init");

    err = audio_frontend_init();
    if (FSP_SUCCESS != err)
    {
        audio_display_text(DISPLAY_STATUS_CTRL, "I2S init failed");
        __BKPT();
    }

    audio_display_text(DISPLAY_LEVEL_CTRL, "SRC: -");
    audio_display_text(DISPLAY_HINT_CTRL, "DST: -");
    audio_state_set(AUDIO_RUNTIME_LISTENING);

    while (1)
    {
        if (g_audio_frame_ready)
        {
            g_audio_frame_ready = false;
            audio_process_frame();

            err = audio_frontend_start_frame();
            if (FSP_SUCCESS != err)
            {
                audio_display_text(DISPLAY_STATUS_CTRL, "I2S restart failed");
                printf("I2S restart failed: %d\n", err);
                R_BSP_SoftwareDelay(200, BSP_DELAY_UNITS_MILLISECONDS);
            }
        }

        R_BSP_SoftwareDelay(5, BSP_DELAY_UNITS_MILLISECONDS);
    }
    
#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

static void wifi_api_test_run(void)
{
    fsp_err_t err;
    char status_line[40];

    printf("\n========== WIFI API TEST START ==========\n");
    printf("SSID: %s\n", APP_AI_WIFI_SSID);

    audio_display_text(DISPLAY_STATUS_CTRL, "WIFI TEST");
    audio_display_text(DISPLAY_LEVEL_CTRL, "Connecting...");
    audio_display_text(DISPLAY_HINT_CTRL, APP_AI_WIFI_SSID);

    err = net_client_init();
    if (FSP_SUCCESS == err)
    {
        err = net_client_connect_wifi(APP_AI_WIFI_SSID, APP_AI_WIFI_PASSWORD);
    }
    if (FSP_SUCCESS == err)
    {
        printf("WIFI API connect success.\n");
        audio_display_text(DISPLAY_STATUS_CTRL, "WIFI OK");
        audio_display_text(DISPLAY_LEVEL_CTRL, "Connected");
        audio_display_text(DISPLAY_HINT_CTRL, APP_AI_WIFI_SSID);
    }
    else
    {
        printf("WIFI API connect failed, err=%d\n", err);
        snprintf(status_line, sizeof(status_line), "ERR:%d", err);
        audio_display_text(DISPLAY_STATUS_CTRL, "WIFI FAIL");
        audio_display_text(DISPLAY_LEVEL_CTRL, status_line);
        audio_display_text(DISPLAY_HINT_CTRL, "Check ssid/pwd");
    }

    printf("=========== WIFI API TEST END ===========\n");
}

static void audio_copy_display_text(char *dest, uint32_t dest_size, const char *text)
{
    uint32_t out_index = 0U;

    if ((NULL == dest) || (0U == dest_size))
    {
        return;
    }

    dest[0] = '\0';
    if (NULL == text)
    {
        return;
    }

    while (('\0' != *text) &&
           (out_index < (dest_size - 1U)) &&
           (out_index < APP_AI_DISPLAY_TEXT_MAX_LEN))
    {
        char ch = *text++;

        if (('"') == ch || ('\r' == ch) || ('\n' == ch) || ('\t' == ch))
        {
            ch = ' ';
        }

        dest[out_index++] = ch;
    }

    dest[out_index] = '\0';
}

static void audio_display_text(const char *control, const char *text)
{
    char cmd[128];
    char safe_text[APP_AI_DISPLAY_TEXT_MAX_LEN + 1U];

    if ((NULL == control) || (NULL == text))
    {
        return;
    }

    audio_copy_display_text(safe_text, sizeof(safe_text), text);
    snprintf(cmd, sizeof(cmd), "%s.txt=\"%s\"", control, safe_text);
    uart2_printf(cmd);
    uart2_putchar(0xFF);
    uart2_putchar(0xFF);
    uart2_putchar(0xFF);
}

static void audio_display_state(audio_runtime_state_t state)
{
    switch (state)
    {
        case AUDIO_RUNTIME_BOOT:
        {
            audio_display_text(DISPLAY_STATUS_CTRL, "BOOT");
            break;
        }

        case AUDIO_RUNTIME_LISTENING:
        {
            audio_display_text(DISPLAY_STATUS_CTRL, "LISTEN");
            break;
        }

        case AUDIO_RUNTIME_WAKEUP:
        {
            audio_display_text(DISPLAY_STATUS_CTRL, "WAKE");
            break;
        }

        case AUDIO_RUNTIME_RECORDING:
        {
            audio_display_text(DISPLAY_STATUS_CTRL, "RECORD");
            break;
        }

        case AUDIO_RUNTIME_ASR:
        {
            audio_display_text(DISPLAY_STATUS_CTRL, "ASR");
            break;
        }

        case AUDIO_RUNTIME_TRANSLATE:
        {
            audio_display_text(DISPLAY_STATUS_CTRL, "TRANSLATE");
            break;
        }

        case AUDIO_RUNTIME_SHOW_RESULT:
        {
            audio_display_text(DISPLAY_STATUS_CTRL, "DONE");
            break;
        }

        case AUDIO_RUNTIME_ERROR:
        {
            audio_display_text(DISPLAY_STATUS_CTRL, "ERROR");
            break;
        }

        default:
        {
            audio_display_text(DISPLAY_STATUS_CTRL, "UNKNOWN");
            break;
        }
    }
}

static void audio_show_translation_lines(void)
{
    char src_line[128];
    char dst_line[128];

    snprintf(src_line, sizeof(src_line), "SRC:%s", g_source_text);
    snprintf(dst_line, sizeof(dst_line), "DST:%s", g_translated_text);

    audio_display_text(DISPLAY_LEVEL_CTRL, src_line);
    audio_display_text(DISPLAY_HINT_CTRL, dst_line);
}

static void audio_state_set(audio_runtime_state_t state)
{
    g_audio_state = state;
    audio_display_state(state);
}

static void audio_reset_capture_session(void)
{
    g_wake_streak = 0;
    g_record_frame_count = 0;
    g_record_level_sum = 0;
}

static fsp_err_t audio_cloud_prepare(void)
{
    fsp_err_t err;

    if (g_cloud_connected)
    {
        return FSP_SUCCESS;
    }

    if ((0 == strcmp(APP_AI_WIFI_SSID, "your_ssid")) || (0 == strcmp(APP_AI_WIFI_PASSWORD, "your_password")))
    {
        return FSP_ERR_NOT_OPEN;
    }

    err = net_client_init();
    if (FSP_SUCCESS == err)
    {
        err = net_client_connect_wifi(APP_AI_WIFI_SSID, APP_AI_WIFI_PASSWORD);
    }
    if (FSP_SUCCESS == err)
    {
        g_cloud_connected = true;
    }

    return err;
}

static fsp_err_t audio_frontend_init(void)
{
    fsp_err_t err;

    memset(g_audio_rx_buffer, 0, sizeof(g_audio_rx_buffer));
    memset(g_audio_tx_dummy, 0, sizeof(g_audio_tx_dummy));
    g_audio_frame_ready = false;
    g_audio_rx_events = 0;
    g_audio_error_events = 0;
    g_audio_state = AUDIO_RUNTIME_BOOT;
    g_cloud_connected = false;
    g_wake_streak = 0;
    g_record_frame_count = 0;
    g_record_level_sum = 0;
    g_result_hold_count = 0;
    g_cooldown_count = 0;
    memset(g_source_text, 0, sizeof(g_source_text));
    memset(g_translated_text, 0, sizeof(g_translated_text));

    err = g_i2s0.p_api->open(g_i2s0.p_ctrl, g_i2s0.p_cfg);
    if (FSP_SUCCESS != err)
    {
        printf("g_i2s0 open failed: %d\n", err);
        return err;
    }

    return audio_frontend_start_frame();
}

static fsp_err_t audio_frontend_start_frame(void)
{
    return g_i2s0.p_api->writeRead(g_i2s0.p_ctrl, g_audio_tx_dummy, g_audio_rx_buffer, sizeof(g_audio_rx_buffer));
}

static uint32_t audio_calculate_level(const int16_t *buffer, uint32_t samples)
{
    uint32_t sum = 0;

    for (uint32_t i = 0; i < samples; i++)
    {
        int32_t sample = buffer[i];

        if (sample < 0)
        {
            sample = -sample;
        }

        sum += (uint32_t) sample;
    }

    return sum / samples;
}

static void audio_process_frame(void)
{
    static uint32_t display_counter = 0;
    uint32_t level = audio_calculate_level(g_audio_rx_buffer, AUDIO_FRAME_SAMPLES);
    fsp_err_t err = FSP_SUCCESS;

    if (g_cooldown_count > 0U)
    {
        g_cooldown_count--;
    }

    switch (g_audio_state)
    {
        case AUDIO_RUNTIME_BOOT:
        {
            audio_state_set(AUDIO_RUNTIME_LISTENING);
            break;
        }

        case AUDIO_RUNTIME_LISTENING:
        {
            if ((level > AUDIO_WAKE_LEVEL_TRIGGER) && (0U == g_cooldown_count))
            {
                g_wake_streak++;
            }
            else
            {
                g_wake_streak = 0;
            }

            if (g_wake_streak >= AUDIO_WAKE_CONSECUTIVE_FRAMES)
            {
                audio_reset_capture_session();
                audio_state_set(AUDIO_RUNTIME_WAKEUP);
                audio_display_text(DISPLAY_LEVEL_CTRL, "SRC:wakeup");
                audio_display_text(DISPLAY_HINT_CTRL, "DST:recording...");
            }

            break;
        }

        case AUDIO_RUNTIME_WAKEUP:
        {
            audio_state_set(AUDIO_RUNTIME_RECORDING);
            break;
        }

        case AUDIO_RUNTIME_RECORDING:
        {
            g_record_frame_count++;
            g_record_level_sum += level;

            if (g_record_frame_count >= AUDIO_RECORD_TARGET_FRAMES)
            {
                uint32_t avg_level = g_record_level_sum / g_record_frame_count;
                memset(g_source_text, 0, sizeof(g_source_text));
                memset(g_translated_text, 0, sizeof(g_translated_text));

                audio_state_set(AUDIO_RUNTIME_ASR);
                err = app_ai_asr_stub(avg_level, g_source_text, sizeof(g_source_text));
                if (FSP_SUCCESS != err)
                {
                    snprintf(g_source_text, sizeof(g_source_text), "asr failed");
                }

                if (FSP_SUCCESS == err)
                {
                    audio_state_set(AUDIO_RUNTIME_TRANSLATE);
                    err = audio_cloud_prepare();

                    if (FSP_SUCCESS == err)
                    {
                        err = app_ai_translate_pipeline(g_source_text,
                                                        APP_AI_TRANSLATE_FROM_LANG,
                                                        APP_AI_TRANSLATE_TO_LANG,
                                                        g_translated_text,
                                                        sizeof(g_translated_text));
                    }
                    else
                    {
                        snprintf(g_translated_text, sizeof(g_translated_text), "config wifi first");
                    }
                }

                if (FSP_SUCCESS != err)
                {
                    if (FSP_ERR_NOT_OPEN == err)
                    {
                        snprintf(g_translated_text, sizeof(g_translated_text), "config wifi first");
                    }
                    else
                    {
                        snprintf(g_translated_text, sizeof(g_translated_text), "translate err:%d", err);
                    }

                    audio_state_set(AUDIO_RUNTIME_ERROR);
                }
                else
                {
                    audio_state_set(AUDIO_RUNTIME_SHOW_RESULT);
                }

                audio_show_translation_lines();
                g_result_hold_count = AUDIO_RESULT_HOLD_FRAMES;
                g_cooldown_count = AUDIO_COOLDOWN_FRAMES;
                audio_reset_capture_session();
            }

            break;
        }

        case AUDIO_RUNTIME_ASR:
        case AUDIO_RUNTIME_TRANSLATE:
        {
            break;
        }

        case AUDIO_RUNTIME_SHOW_RESULT:
        case AUDIO_RUNTIME_ERROR:
        {
            if (g_result_hold_count > 0U)
            {
                g_result_hold_count--;
            }
            else
            {
                audio_state_set(AUDIO_RUNTIME_LISTENING);
                audio_display_text(DISPLAY_LEVEL_CTRL, "SRC:-");
                audio_display_text(DISPLAY_HINT_CTRL, "DST:-");
            }

            break;
        }

        default:
        {
            audio_state_set(AUDIO_RUNTIME_ERROR);
            break;
        }
    }

    display_counter++;

    if ((display_counter % AUDIO_STATUS_UPDATE_INTERVAL) == 0U)
    {
        printf("I2S frames=%lu level=%lu wake=%lu state=%d errors=%lu\n",
               (unsigned long) g_audio_rx_events,
               (unsigned long) level,
               (unsigned long) g_wake_streak,
               (int) g_audio_state,
               (unsigned long) g_audio_error_events);
    }
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&g_ioport_ctrl, &IOPORT_CFG_NAME);
    }
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
